TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          finishersDefinition:
            SalesforceFinisher:
              implementationClassName: 'JWeiland\Form2salesforce\Domain\Finisher\SalesforceFinisher'
